build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

console-reports:
  active: true

output-reports:
  active: true

processors:
  active: true

comments:
  active: true

complexity:
  active: true
  LongParameterList:
    active: true
    functionThreshold: 6
    constructorThreshold: 3
  TooManyFunctions:
    active: true
    thresholdInFiles: 11
    thresholdInClasses: 11
    thresholdInInterfaces: 11
    thresholdInObjects: 11

empty-blocks:
  active: true

exceptions:
  active: true

naming:
  active: true

performance:
  active: true

style:
  active: true

potential-bugs:
  active: true
